[workspace]
members = [
    "crates/texo-cli",
    "crates/texo-flow",
    "crates/texo-model",
    "crates/texo-pnr",
    "crates/texo-struo",
    "crates/texo-target-ecp5",
    "crates/texo-timing",
]
default-members = ["crates/texo-cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
authors = ["Texo contributors"]

[workspace.dependencies]
celox = { version = "=0.3.1", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
struo-celox = { git = "https://github.com/fabrica-eda/struo.git", rev = "8dad8c2e27f4dacd6283bb4015ad99208618c228" }
struo-ir = { git = "https://github.com/fabrica-eda/struo.git", rev = "8dad8c2e27f4dacd6283bb4015ad99208618c228" }
struo-target-ecp5 = { git = "https://github.com/fabrica-eda/struo.git", rev = "8dad8c2e27f4dacd6283bb4015ad99208618c228" }
texo-flow = { path = "crates/texo-flow" }
texo-model = { path = "crates/texo-model" }
texo-pnr = { path = "crates/texo-pnr" }
texo-struo = { path = "crates/texo-struo" }
texo-target-ecp5 = { path = "crates/texo-target-ecp5" }
texo-timing = { path = "crates/texo-timing" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[profile.release]
codegen-units = 1
lto = "thin"
