[package]
name = "texo-target-ecp5"
description = "Project Trellis architecture import for Texo"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true

[dependencies]
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
texo-model.workspace = true
texo-pnr.workspace = true

[dev-dependencies]
struo-ir.workspace = true
struo-target-ecp5.workspace = true
texo-struo.workspace = true

[lints]
workspace = true
