[package]
name = "texo-pnr"
description = "Placement and routing algorithms for Texo"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = ["crates-io"]

[dependencies]
libm.workspace = true
rayon.workspace = true
rustdct.workspace = true
texo-model.workspace = true

[lints]
workspace = true
