[package]
name = "texo-cli"
description = "Command-line interface for Texo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "texo"
path = "src/main.rs"

[dependencies]
texo-flow.workspace = true
texo-model.workspace = true
texo-target-ecp5.workspace = true

[lints]
workspace = true
