[package]
name = "texo-cli"
description = "Command-line interface for Texo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "texo"
path = "src/main.rs"

[dependencies]
celox.workspace = true
serde_json.workspace = true
struo-celox.workspace = true
struo-example-axi4-smartconnect.workspace = true
struo-ir.workspace = true
struo-synth.workspace = true
struo-target-ecp5.workspace = true
texo-flow.workspace = true
texo-model.workspace = true
texo-struo.workspace = true
texo-target-ecp5.workspace = true

[lints]
workspace = true
