[package]
name = "texo-cli"
description = "Command-line interface for Texo"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "texo"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
struo-frontend-veryl.workspace = true
struo-rtl.workspace = true
struo-synth.workspace = true
struo-target-ecp5.workspace = true
texo-flow.workspace = true
texo-model.workspace = true
texo-struo.workspace = true
texo-target-ecp5.workspace = true
ureq.workspace = true
veryl-analyzer.workspace = true
veryl-metadata.workspace = true
veryl-parser.workspace = true
zstd.workspace = true

[dev-dependencies]
celox.workspace = true
struo-celox.workspace = true
struo-example-axi4-smartconnect.workspace = true
struo-ir.workspace = true

[lints]
workspace = true
